[theme]
primaryColor = "#16794A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F7"
textColor = "#1B2631"
font = "sans serif"
baseRadius = "medium"

[client]
toolbarMode = "minimal"

[server]
headless = true

[browser]
gatherUsageStats = false
